Algoritmo "Somadosvalores"
// Disciplina  : Lógica de Programação com JavaScript]
// Professor   : Jailson Consta
// Descrição   : Somar dois valores e exibir um resultado
// Autor(a)    : Vitor Pereira Martins
// Data atual  : 09/09/2022
Var
// Seção de Declarações das variáveis 
Numero1:inteiro
Numero2:inteiro
RDS:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Bom Dia")
Escreval("Digite um numero para ser somado")
Leia(Numero1)
Escreval("digite outro numero para ser somado")
Leia(Numero2)
RDS<-Numero1+Numero2)
Escreval("O valor da soma dos valores é :", RDS)

Fimalgoritmo
