Algoritmo "Testecaractere"
// Disciplina   : [Lógica de Programação com JavaScrpt]
// Professor   : Jailson
// Descrição   : Teste caractere
// Autor(a)    : Vitor Pereira Martins
// Data atual  : 05/09/2022
Var
// Seção de Declarações das variáveis
  Nome:caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Bom dia")
Escreval("digite Seu nome :")
Leia(Nome)
Escreval("O nome digitado é :",Nome)
Fimalgoritmo